name: Build and test Search.gov Website

on: [push]

jobs:
  build:
    name: Install, build and test site with pa11y-ci and htmlproofer.
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LANGUAGE: en_US
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Setup ruby env.
        run: |
          sudo apt-get update;
          sudo apt-get install --reinstall -y locales;
          sudo sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen;
          sudo locale-gen en_US.UTF-8;
        

      - name: Install ruby.
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install node.js.
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM dependencies.
        run: npm install

      - name: Build and start up jekyll server.
        run: npm run clean && npm run build && npm run start-detached

#      Temporarily disabling pally-ci and htmlproofer
#      - name: Run pa11y-ci.
#        run: npm run pa11y-ci:sitemap || true
#
#      - name: Run htmlproofer.
#        run: npm run htmlproofer || true
